fix(deps): update dependency io.sentry:sentry-android to v7.18.0 (#5140)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[io.sentry:sentry-android](https://redirect.github.com/getsentry/sentry-java)
| `7.14.0` -> `7.18.0` |
[![age](https://developer.mend.io/api/mc/badges/age/maven/io.sentry:sentry-android/7.18.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/io.sentry:sentry-android/7.18.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/io.sentry:sentry-android/7.14.0/7.18.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/io.sentry:sentry-android/7.14.0/7.18.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

> [!WARNING]
> Some dependencies could not be looked up. Check the Dependency
Dashboard for more information.

---

### Release Notes

<details>
<summary>getsentry/sentry-java (io.sentry:sentry-android)</summary>

###
[`v7.18.0`](https://redirect.github.com/getsentry/sentry-java/blob/HEAD/CHANGELOG.md#7180)

[Compare
Source](https://redirect.github.com/getsentry/sentry-java/compare/7.17.0...7.18.0)

##### Features

- Android 15: Add support for 16KB page sizes
([#&#8203;3620](https://redirect.github.com/getsentry/sentry-java/pull/3620))
- See https://developer.android.com/guide/practices/page-sizes for more
details
- Session Replay: Add `beforeSendReplay` callback
([#&#8203;3855](https://redirect.github.com/getsentry/sentry-java/pull/3855))
- Session Replay: Add support for masking/unmasking view containers
([#&#8203;3881](https://redirect.github.com/getsentry/sentry-java/pull/3881))

##### Fixes

- Avoid collecting normal frames
([#&#8203;3782](https://redirect.github.com/getsentry/sentry-java/pull/3782))
- Ensure android initialization process continues even if options
configuration block throws an exception
([#&#8203;3887](https://redirect.github.com/getsentry/sentry-java/pull/3887))
- Do not report parsing ANR error when there are no threads
([#&#8203;3888](https://redirect.github.com/getsentry/sentry-java/pull/3888))
- This should significantly reduce the number of events with message
"Sentry Android SDK failed to parse system thread dump..." reported
- Session Replay: Disable replay in session mode when rate limit is
active
([#&#8203;3854](https://redirect.github.com/getsentry/sentry-java/pull/3854))

##### Dependencies

- Bump Native SDK from v0.7.2 to v0.7.8
([#&#8203;3620](https://redirect.github.com/getsentry/sentry-java/pull/3620))
-
[changelog](https://redirect.github.com/getsentry/sentry-native/blob/master/CHANGELOG.md#078)
-
[diff](https://redirect.github.com/getsentry/sentry-native/compare/0.7.2...0.7.8)

###
[`v7.17.0`](https://redirect.github.com/getsentry/sentry-java/blob/HEAD/CHANGELOG.md#7170)

[Compare
Source](https://redirect.github.com/getsentry/sentry-java/compare/7.16.0...7.17.0)

##### Features

- Add meta option to set the maximum amount of breadcrumbs to be logged.
([#&#8203;3836](https://redirect.github.com/getsentry/sentry-java/pull/3836))
- Use a separate `Random` instance per thread to improve SDK performance
([#&#8203;3835](https://redirect.github.com/getsentry/sentry-java/pull/3835))

##### Fixes

- Using MaxBreadcrumb with value 0 no longer crashes.
([#&#8203;3836](https://redirect.github.com/getsentry/sentry-java/pull/3836))
- Accept manifest integer values when requiring floating values
([#&#8203;3823](https://redirect.github.com/getsentry/sentry-java/pull/3823))
- Fix standalone tomcat jndi issue
([#&#8203;3873](https://redirect.github.com/getsentry/sentry-java/pull/3873))
- Using Sentry Spring Boot on a standalone tomcat caused the following
error:
- Failed to bind properties under 'sentry.parsed-dsn' to io.sentry.Dsn

###
[`v7.16.0`](https://redirect.github.com/getsentry/sentry-java/blob/HEAD/CHANGELOG.md#7160)

[Compare
Source](https://redirect.github.com/getsentry/sentry-java/compare/7.15.0...7.16.0)

##### Features

- Add meta option to attach ANR thread dumps
([#&#8203;3791](https://redirect.github.com/getsentry/sentry-java/pull/3791))

##### Fixes

- Cache parsed Dsn
([#&#8203;3796](https://redirect.github.com/getsentry/sentry-java/pull/3796))
- fix invalid profiles when the transaction name is empty
([#&#8203;3747](https://redirect.github.com/getsentry/sentry-java/pull/3747))
- Deprecate `enableTracing` option
([#&#8203;3777](https://redirect.github.com/getsentry/sentry-java/pull/3777))
- Vendor `java.util.Random` and replace `java.security.SecureRandom`
usages
([#&#8203;3783](https://redirect.github.com/getsentry/sentry-java/pull/3783))
- Fix potential ANRs due to NDK scope sync
([#&#8203;3754](https://redirect.github.com/getsentry/sentry-java/pull/3754))
- Fix potential ANRs due to NDK System.loadLibrary calls
([#&#8203;3670](https://redirect.github.com/getsentry/sentry-java/pull/3670))
- Fix slow `Log` calls on app startup
([#&#8203;3793](https://redirect.github.com/getsentry/sentry-java/pull/3793))
- Fix slow Integration name parsing
([#&#8203;3794](https://redirect.github.com/getsentry/sentry-java/pull/3794))
- Session Replay: Reduce startup and capture overhead
([#&#8203;3799](https://redirect.github.com/getsentry/sentry-java/pull/3799))
- Load lazy fields on init in the background
([#&#8203;3803](https://redirect.github.com/getsentry/sentry-java/pull/3803))
- Replace setOf with HashSet.add
([#&#8203;3801](https://redirect.github.com/getsentry/sentry-java/pull/3801))

##### Breaking changes

- The method `addIntegrationToSdkVersion(Ljava/lang/Class;)V` has been
removed from the core (`io.sentry:sentry`) package. Please make sure all
of the packages (e.g. `io.sentry:sentry-android-core`,
`io.sentry:sentry-android-fragment`, `io.sentry:sentry-okhttp` and
others) are all aligned and using the same version to prevent the
`NoSuchMethodError` exception.

###
[`v7.15.0`](https://redirect.github.com/getsentry/sentry-java/blob/HEAD/CHANGELOG.md#7150)

[Compare
Source](https://redirect.github.com/getsentry/sentry-java/compare/7.14.0...7.15.0)

##### Features

- Add support for `feedback` envelope header item type
([#&#8203;3687](https://redirect.github.com/getsentry/sentry-java/pull/3687))
- Add breadcrumb.origin field
([#&#8203;3727](https://redirect.github.com/getsentry/sentry-java/pull/3727))
- Session Replay: Add options to selectively mask/unmask views captured
in replay. The following options are available:
([#&#8203;3689](https://redirect.github.com/getsentry/sentry-java/pull/3689))
- `android:tag="sentry-mask|sentry-unmask"` in XML or
`view.setTag("sentry-mask|sentry-unmask")` in code tags
- if you already have a tag set for a view, you can set a tag by id:
`<tag android:id="@&#8203;id/sentry_privacy"
android:value="mask|unmask"/>` in XML or
`view.setTag(io.sentry.android.replay.R.id.sentry_privacy,
"mask|unmask")` in code
- `view.sentryReplayMask()` or `view.sentryReplayUnmask()` extension
functions
- mask/unmask `View`s of a certain type by adding fully-qualified
classname to one of the lists
`options.experimental.sessionReplay.addMaskViewClass()` or
`options.experimental.sessionReplay.addUnmaskViewClass()`. Note, that
all of the view subclasses/subtypes will be masked/unmasked as well
- For example, (this is already a default behavior) to mask all
`TextView`s and their subclasses (`RadioButton`, `EditText`, etc.):
`options.experimental.sessionReplay.addMaskViewClass("android.widget.TextView")`
- If you're using code obfuscation, adjust your proguard-rules
accordingly, so your custom view class name is not minified
- Session Replay: Support Jetpack Compose masking
([#&#8203;3739](https://redirect.github.com/getsentry/sentry-java/pull/3739))
- To selectively mask/unmask
[@&#8203;Composables](https://redirect.github.com/Composables), use
`Modifier.sentryReplayMask()` and `Modifier.sentryReplayUnmask()`
modifiers
- Session Replay: Mask `WebView`, `VideoView` and
`androidx.media3.ui.PlayerView` by default
([#&#8203;3775](https://redirect.github.com/getsentry/sentry-java/pull/3775))

##### Fixes

- Avoid stopping appStartProfiler after application creation
([#&#8203;3630](https://redirect.github.com/getsentry/sentry-java/pull/3630))
- Session Replay: Correctly detect dominant color for `TextView`s with
Spans
([#&#8203;3682](https://redirect.github.com/getsentry/sentry-java/pull/3682))
- Fix ensure Application Context is used even when SDK is initialized
via Activity Context
([#&#8203;3669](https://redirect.github.com/getsentry/sentry-java/pull/3669))
- Fix potential ANRs due to `Calendar.getInstance` usage in Breadcrumbs
constructor
([#&#8203;3736](https://redirect.github.com/getsentry/sentry-java/pull/3736))
- Fix potential ANRs due to default integrations
([#&#8203;3778](https://redirect.github.com/getsentry/sentry-java/pull/3778))
- Lazily initialize heavy `SentryOptions` members to avoid ANRs on app
start
([#&#8203;3749](https://redirect.github.com/getsentry/sentry-java/pull/3749))

*Breaking changes*:

- `options.experimental.sessionReplay.errorSampleRate` was renamed to
`options.experimental.sessionReplay.onErrorSampleRate`
([#&#8203;3637](https://redirect.github.com/getsentry/sentry-java/pull/3637))
- Manifest option `io.sentry.session-replay.error-sample-rate` was
renamed to `io.sentry.session-replay.on-error-sample-rate`
([#&#8203;3637](https://redirect.github.com/getsentry/sentry-java/pull/3637))
- Change `redactAllText` and `redactAllImages` to `maskAllText` and
`maskAllImages`
([#&#8203;3741](https://redirect.github.com/getsentry/sentry-java/pull/3741))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/simpledotorg/simple-android).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xOS4wIiwidXBkYXRlZEluVmVyIjoiMzkuMTkuMCIsInRhcmdldEJyYW5jaCI6Im1hc3RlciIsImxhYmVscyI6W119-->

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Sasikanth Miriyampalli <hello@sasikanth.dev>